### ISSUE TITLE
(Re-)enable CORS for JSON requests

### ISSUE THREAD

**Issue by hcayless** [isawnyu/pleiades-json#1]
Pleiades used to permit cross-origin requests for JSON data until quite recently. It seems to have stopped though. If this isn't a policy decision, can you enable CORS again so other sites can load json form Pleiades via a browser-based request?

**Comment by paregorios** [comment]
Closing here after migrating to the primary issue tracker: https://github.com/isawnyu/pleiades-gazetteer/issues/170
